spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intelligent-consultation-platform
    username: root
    password: 123456
server:
  port: 8123

deepseek:
  api-key: sk-f00b09318c0f42cdb27ed5d62216bd55
  base-url: https://api.deepseek.com
  model: deepseek-chat
  timeout: 60000
